package com.example.fyp_1.DataStructure;

public enum TruckStatus {
    TRUCK_BROKEN, TRUCK_DEADHEADING, TRUCK_HALFLOAD_DEADHEADING, TRUCK_XSHIPPING,
    TRUCK_HALFLOAD_XSHIPPING, TRUCK_AVAILABLE, TRUCK_QUEUEING
}
