package com.example.fyp_1;

public enum EventType {
    TASK_IMPORT,
    YC_WORKING_POINT_ARRIVAL,
    QC_WORKING_POINT_ARRIVAL,
    CRANE_UNLOADING_FROM_VEHICLE_SUCCESS,
    CRANE_PUTTING_TO_VEHICLE_SUCCESS,
    CRANE_UNLOADING_FROM_VEHICLE_FINISH,
    CRANE_PUTTING_TO_VEHICLE_FINISH
}
